/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package eu.ggnet.dwoss.redtape.document.complaint;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;

import eu.ggnet.saft.core.Client;

import eu.ggnet.dwoss.mandator.MandatorSupporter;

import eu.ggnet.dwoss.redtape.entity.Position;
import eu.ggnet.dwoss.redtape.entity.PositionBuilder;

import eu.ggnet.dwoss.rules.PositionType;

import eu.ggnet.dwoss.redtape.document.AfterInvoicePosition;
import eu.ggnet.dwoss.util.CloseType;
import eu.ggnet.dwoss.util.IPreClose;

import static eu.ggnet.dwoss.rules.PositionType.COMMENT;

/**
 *
 * @author pascal.perau
 */
public class ComplaintView extends javax.swing.JPanel implements IPreClose{

    private List<AfterInvoicePosition> complaintPositions;

    /** Creates new form ComplaintView */
    public ComplaintView(List<AfterInvoicePosition> complaintPositions) {
        initComponents();
        this.complaintPositions = complaintPositions;
        afterInvoiceTablePanel.setTableModel(new ComplaintTableModel(complaintPositions));

    }

    public List<Position> getPositions() {
        List<Position> positions = new ArrayList<>();
        for (AfterInvoicePosition afterInvoicePosition : complaintPositions) {
            if ( afterInvoicePosition.isParticipant() ) {
               positions.add(afterInvoicePosition.getPosition());
            }
        }
        if ( afterInvoiceTablePanel.getComment() != null && !afterInvoiceTablePanel.getComment().trim().equals("") )
            positions.add(new PositionBuilder().setType(PositionType.COMMENT).setName("Grund/Beschreibung")
                    .setBookingAccount(Client.lookup(MandatorSupporter.class).loadPostLedger().get(COMMENT).orElse(-1))
                    .setDescription(afterInvoiceTablePanel.getComment()).createPosition());
        return positions;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        afterInvoiceTablePanel = new eu.ggnet.dwoss.redtape.document.AfterInvoiceTablePanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(afterInvoiceTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(afterInvoiceTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private eu.ggnet.dwoss.redtape.document.AfterInvoiceTablePanel afterInvoiceTablePanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean pre(CloseType type) {
        if ( type == CloseType.OK && getPositions().isEmpty() ) {
            JOptionPane.showMessageDialog(this, "keine Positionen zur Gutschrift gewählt");
            return false;
        }
        return true;
    }
}
