package tryout.support;

import java.awt.BorderLayout;

import org.openide.util.lookup.ServiceProvider;

import eu.ggnet.saft.core.MainComponent;

/**
 *
 * @author oliver.guenther
 */
@ServiceProvider(service = MainComponent.class)
public class TryoutMainPanel1 extends javax.swing.JPanel implements MainComponent {

    /** Creates new form TryoutMainPanel1 */
    public TryoutMainPanel1() {
        initComponents();
    }

    @Override
    public String getLayoutHint() {
        return BorderLayout.WEST;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ein Text");
        add(jLabel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
