/*
 * Copyright (C) 2014 GG-Net GmbH - Oliver Günther
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package eu.ggnet.dwoss.receipt.ui.product;

import java.awt.BorderLayout;
import java.util.Objects;

import eu.ggnet.dwoss.receipt.ee.ProductProcessor.SpecAndModel;
import eu.ggnet.dwoss.spec.ee.entity.Monitor;

public class MonitorView extends AbstractView {

    private BasicView basicView;

    private DisplayPanel displayView;

    /**
     * Creates new form PartsMonitorPanel
     */
    public MonitorView() {
        initComponents();
        displayView = new DisplayPanel();
        displayPanel.add(displayView, BorderLayout.CENTER);

        basicView = new BasicView();
        basicViewPanel.add(basicView, BorderLayout.CENTER);
        basicViewPanel.setPreferredSize(basicView.getPreferredSize());
    }

    @Override
    public void accept(SpecAndModel sam) {
        Monitor monitor = (Monitor)Objects.requireNonNull(sam, "sam must not be null").spec();
        displayView.setDisplay(monitor.getDisplay());
        basicView.accept(sam);
    }

    @Override
    public SpecAndModel getResult() {
        SpecAndModel sam = basicView.getResult();
        Monitor monitor = (Monitor)sam.spec();
        monitor.setDisplay(displayView.getDisplay());
        return new SpecAndModel(monitor, sam.model(), sam.gtin());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayPanel = new javax.swing.JPanel();
        basicViewPanel = new javax.swing.JPanel();

        displayPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        displayPanel.setLayout(new java.awt.BorderLayout());

        basicViewPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        basicViewPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(displayPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
            .addComponent(basicViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(displayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(basicViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basicViewPanel;
    private javax.swing.JPanel displayPanel;
    // End of variables declaration//GEN-END:variables

}
