/* 
 * Copyright (C) 2014 GG-Net GmbH - Oliver Günther
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package eu.ggnet.dwoss.redtapext.ui.cao.common;

import eu.ggnet.dwoss.util.CloseType;
import eu.ggnet.dwoss.util.IPreClose;

/**
 * A simple JPanel containing a Textarea.
 * @author pascal.perau
 */
public class StringAreaView extends javax.swing.JPanel implements IPreClose{
    
    String theString = "";
    
    /** Creates new form StringAreaView */
    public StringAreaView(String preset) {
        initComponents();
        if(preset != null){
            stringArea.setText(preset);
        }
    }
    
    public String getText(){
        return theString;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        stringArea = new javax.swing.JTextArea();

        stringArea.setColumns(20);
        stringArea.setLineWrap(true);
        stringArea.setRows(5);
        stringArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(stringArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea stringArea;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean pre(CloseType type) {
        if(type == CloseType.CANCEL) return true;
        else{
            theString = stringArea.getText();
            return true;
        }
    }
}
