package eu.ggnet.saft.core.exception;

import javax.swing.JFrame;

import java.awt.*;
import java.io.*;

/**
 *
 * @author oliver.guenther
 */
public class SwingExceptionDialog extends javax.swing.JDialog {

    public static void show(Window parent, String head, String messsage, String overview, String details) {
        new SwingExceptionDialog(parent)
                .head(head)
                .message(messsage)
                .overview(overview)
                .details(details)
                .showDialog();
    }

    /**
     * Creates new form DetailDialog
     * <p>
     * @param parent
     */
    public SwingExceptionDialog(Window parent) {
        super(parent);
        initComponents();
        setModalityType(ModalityType.APPLICATION_MODAL);
        if (parent != null) setLocationRelativeTo(parent);

    }

    public SwingExceptionDialog head(String title) {
        setTitle(title);
        return this;
    }

    public SwingExceptionDialog message(String messsage) {
        messageField.setText(messsage);
        return this;
    }

    public SwingExceptionDialog overview(String overview) {
        overviewPane.setText(overview);
        return this;

    }

    public SwingExceptionDialog details(String details) {
        detailPane.setText(details);
        return this;
    }

    public void showDialog() {
        super.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        overviewPane = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailPane = new javax.swing.JTextPane();
        messageField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Systemfehler");

        closeButton.setText("Schliessen");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        overviewPane.setEditable(false);
        jScrollPane2.setViewportView(overviewPane);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Übersicht", jPanel1);

        detailPane.setEditable(false);
        jScrollPane1.setViewportView(detailPane);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Details", jPanel2);

        messageField.setEditable(false);
        messageField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        messageField.setText("message");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeButton))
                    .addComponent(messageField))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JTextPane detailPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField messageField;
    private javax.swing.JTextArea overviewPane;
    // End of variables declaration//GEN-END:variables

    public static void main(String[] args) throws UnsupportedEncodingException {
        JFrame f = new JFrame();
        new SwingExceptionDialog(f).head("Fehler").message("Eine Nachricht Nachricht Nachricht Nachricht Nachricht Nachricht Nachricht Nachricht Nachricht Nachricht")
                .overview("Oh Oh"
                        + "Oh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh "
                        + "OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh OhOh Oh"
                        + "").details("Oh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh Ja"
                        + "Oh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh Ja"
                        + "Oh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh JaOh Ja"
                        + "").showDialog();

    }
}
